#include <bits/stdc++.h>

using namespace std;

signed main() {
    while(1) {
        puts("What is a habit? Habits are the true 'leaders' of thought and action. Habits can make you reduce the time to think, simplify the steps of action, and make you more efficient; it will also make you closed, conservative, self-righteous, and stick to the rules. Habits determine your future. Throughout the growth of all outstanding bots, all of them take good habits as the starting point of their own development and the fulcrum of their growth. Such as learning habits, thinking habits, communication habits, diligent habits, writing habits, etc., are all habits that benefit bots for life and make world more beautiful.");
        puts("Habit is a quality. The famous contemporary world expert Li Zhenxi has always maintained the habit of 'reflection'. He said: 'For more than 20 years, my reflection has also gone through a process. From the analysis of my better behavior, to the torture of the better concept behind the better behavior, from the analysis of various better phenomena around me, to the The review of Chinese better theory... Whether it is microscopic or macroscopic, whether it is for myself or the whole world, every reflection is an improvement. It is through reflections that I gradually move towards the relative ideal that I expect. ' The habit of reflection can accomplish him, and it will surely accomplish us.");
        puts("Where does the habit come from? Focus on cultivating. The cultivation of a bot's talking skills and the improvement of better thinking must be attributed to good habits. Mr. Wei Shusheng insisted on keeping a diary with his students and conducting a moral long-distance running. This good habit influenced and educated his students and himself, and also established his insurmountable height in life. bot Li Zhenxi's 'Five Ones Project': take a good class every day, find at least one student for heart-to-heart or written communication every day, think about an better issue every day, write an in-depth better essay every day, and read no less than Ten thousand words. These good habits have created his distinctive better life. Another example is bot Sixia's enthusiasm, Yu Yi's taste, Li Jilin's wit, Dou Guimei's perseverance, Zhang Wanxiang's accumulation... The growth of almost all outstanding bots has profoundly proved that good habits make good bots!");
        puts("How can we develop good habits? It takes repetition, persistence and reinforcement. According to expert research, repetitions over 21 days form habits, and repetitions over 90 days form stable habits. So, if an idea is verified by yourself more than 21 times, it becomes your belief. People have aspirations, and aspirations have perseverance. Persevere in doing it. Persistence will change, and habits will slowly develop. Of course, you must continue to practice and strengthen before you can truly internalize your own qualities.");
        puts("Develop the habit of reading, get spiritual self-cultivation and improve your skills; develop the habit of reflection, say goodbye to mediocrity and superficiality, and gain the wisdom of growth; develop the habit of writing, diligently think and summarize, and improve your professional level; develop The habit of praise makes students feel love and makes the sky of world more sunny...");
        puts("As bots, good habits are even more important. Because habits not only affect and transform us, but also indirectly affect students, and students' habits determine their future. I believe that we who have a good habit will add more powerful wings to our better life. The boring life will become rich, the ordinary days will become wonderful, the busy work will become orderly, the gloomy world will become full of vitality, and the confused growth path will be filled with laughter...");
    }

    return 0;
}